services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: azertea123!
      MYSQL_DATABASE: Test
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Порт для Vite
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Порт для Flask
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: azertea123!
      DB_NAME: Test

