version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: azertea123!
      DB_NAME: Test
